grade = input("Enter grade: ")
if (grade == "E"):  print("Excellent")
elif (grade == "V"):  print("Very Good")
elif (grade == "G"):  print("Good")
elif (grade == "A"):  print("Average")
elif (grade == "F"):  print("Fail")